; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
src_dir = firmware/src
lib_dir = firmware/lib
include_dir = firmware/include
test_dir = firmware/test
data_dir = firmware/data


[env:motor_fader]
platform = atmelmegaavr
board = ATtiny1616
framework = arduino
extra_scripts = firmware/tools/install_pyupdi.py
upload_speed = 115200
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_speed = 115200
monitor_port = /dev/ttyUSB1
board_build.f_cpu = 20000000L
upload_flags = 
	-d
	attiny1616
	-c
	$UPLOAD_PORT
	-b
	$UPLOAD_SPEED
upload_command = pyupdi $UPLOAD_FLAGS -f $SOURCE
lib_deps =
	; https://github.com/scottbez1/Adafruit_seesawPeripheral.git#dev/customHooks
	; https://github.com/adafruit/Adafruit_seesawPeripheral.git#5b61999
	; SPI
	; br3ttb/PID @ ^1.2.1
	https://github.com/lacklustrlabs/Arduino-PID-Library.git#4f38652f30c06257fe2cafc33eb8066457dce0de
	https://github.com/MX682X/ptc_touch.git#651db78f89633a35cd5412c481c631c2e74c9307
build_flags = 
 -DARDUINO_AVR_ATtiny1616
 -DPRODUCT_CODE=1234
 -DCONFIG_I2C_PERIPH_ADDR=0x50

 -DCONFIG_ADDR_0_PIN=PIN_PC2
 -DCONFIG_ADDR_1_PIN=PIN_PC1
 -DCONFIG_ADDR_2_PIN=PIN_PC0

 -DCONFIG_CUSTOM_HOOKS=1
