; PlatformIO Project Configuration File

[env:lilygo-t-display]
platform = espressif32@6.12
board = esp32dev
framework = arduino

lib_deps =
    madhephaestus/ESP32Servo @ 3.0.9
    adafruit/Adafruit INA3221 Library @ 1.0.1
    bodmer/TFT_eSPI @ 2.5.43
; build_src_filter = +<*> -<.git/> +<../../firmware/src/shared/>
build_flags =
    -I../../firmware/src/shared
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=135
    -DTFT_HEIGHT=240
    -DTFT_MOSI=19
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=16
    -DTFT_RST=23
    -DTFT_BL=4
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=40000000
board_build.filesystem = littlefs
board_build.partitions = default.csv
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_02280A9E-if00-port0